/**
 * Cloudflare Workers entry (P5-04). Wraps the SvelteKit worker generated by adapter-cloudflare and
 * adds a `scheduled` handler: every Cron Trigger in wrangler.jsonc calls POST /api/jobs (protected by
 * CRON_SECRET) through the app itself, so job logic lives in normal SvelteKit server code.
 *   *\/5 * * * *  → release expired stock reservations, expire stale orders, run queued jobs
 *   0 5 * * *     → daily: purge sessions/carts/rate limits, orphan media cleanup, daily report
 */
import app from '../.svelte-kit/cloudflare/_worker.js';

export default {
	fetch: app.fetch,
	async scheduled(event, env, ctx) {
		const base = env.PUBLIC_SITE_URL || 'https://localhost';
		const request = new Request(`${base}/api/jobs?cron=${encodeURIComponent(event.cron)}`, {
			method: 'POST',
			headers: { authorization: `Bearer ${env.CRON_SECRET}`, 'x-cron': event.cron }
		});
		ctx.waitUntil(
			app.fetch(request, env, ctx).then(async (res) => {
				if (!res.ok) console.error(`[cron ${event.cron}] /api/jobs → ${res.status}: ${await res.text()}`);
			})
		);
	}
};
